### ISSUE TITLE
Add Indoor Temp to FreshWDL?

### ISSUE THREAD

**Issue by winedog** [Yerren/FreshWDL#30]
Hi,

Love what you have done with this.  I used to use the old flash version and one thing that was quite handy about it is that you could also display the Indoor temperature and Humidity.  You could even add the Extra Temp Sensors.  All that data is in the clientraw files already.

Any chance to add indoor temp/humidity at the very least?

Thanks!

**Comment by Yerren** [comment]
Hey,

At the moment, it's not quite possible, but I will add it to the to-do list.
I have had someone contribute code to run an extra temperature sensor, which I plan to adjust so that it can display whichever temperature you're after.

Unfortunately it all takes time, but it will be included in the future.

-Yerren

**Comment by Yerren** [comment]
Possibility to add indoor temp has been added.
